### ISSUE TITLE
Cannot compile on OSX

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#1]
Hey @joe-angell and @samhunter , hate to be a noodge, but I'm having issues compiling on both develop and master.
 
(Talking about develop) I had to add `#include<numeric>` to use std::accumulate with common/src/read.cpp, however, after that I am still getting this error when trying to make.

`[ 86%] Linking CXX executable Super-Deduper_test
ld: library not found for -llibhts_common.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Super-Deduper/Super-Deduper_test] Error 1
make[1]: *** [Super-Deduper/CMakeFiles/Super-Deduper_test.dir/all] Error 2`

Also, a ton of warnings with gtest stuff. Is that expected?

Any suggestions?

Thanks, sorry to be a newb with this cmake stuff.

**Comment by joe-angell** [comment]
fixed in d82a307ace4b05b56c62607fb6992616055b5933
