### ISSUE TITLE
RC in Overlapper when compliment needs to be kept

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#104]
One step at a time:

phix-remover only:
$ zcat I1.prOnly_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 2:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-

phix-remover and super-deduper:
$ zcat I1.prAndSd_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-
.. so it looks like it happens in the adapter-trimmer step, as you suspected. In case you're going to send this off for further testing, here's only that pair of reads:

$ zcat ../L5_I1_reads/L5_I1_R1_001.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
TTCAGGTTCAAATTCTCTTTATTTCAAGAACAACAACACTCCTCCGGATACATTGTTGGGTTTTGTGCCCTAAATAAAACCCATTTCGATATAATCAGATTTACTTATTAATAAAGATCAGAAATAA
+
FJJFJJAFJFJJ<JFFFJ<FJJJJJJJJJJJJJFJJJJJ--FJFJJAJAFFJF<-FAFJJJJ--7AJ-FFAJJJFJJJAFFFJ<FAJJJ7F-AJA<FFJJ-FFFFAF<FA-77FFA--AF--AFJJF

$ zcat ../L5_I1_reads/L5_I1_R2_001.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 2:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
+
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-
You were also interested in whether overlapper does the same thing, so here's phix-remover, super-deduper, and overlapper:

(nothing in _SE)

$ zcat I1.olInstead_R1.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
NTTAAAGTTTTTTTTTATATATACATATNTATNTATTATTTTATTATTATTTTTTATATATATATAAACATATTTGACTCGATTAAACCGAGACTTTAGAATAATCAGTAACAAATTAATATGTTCTCGACTTAAATAGAATGCATACAT
+
#AAFFF-FJFFJ-AFJJJJJJFFA<-JF#FJF#-<FF7J-<FFJJJFFFJJA<JJJJJJJJJJFJFFFFJFF<FJ<AJ7FAF-FJ-F--7F-----7A-AFFFFF-7-7AF7F<--7-7AJJ-F<-7---7<7<--7-77F-----7-7-

$ zcat I1.olInstead_R2.fastq.gz | grep -A3 "E00558:100:H7T5FCCXY:5:1101:4117:1450"
@NCCTAAGAGCGACGTA:E00558:100:H7T5FCCXY:5:1101:4117:1450 1:N:0:MATCH:NGCGATAC:NCCTAAGAGCGACGTA:#AAAF-FAFJJFJJJJ:CCAAAGT:JAAJJFA
TTCAGGTTCAAATTCTCTTTATTTCAAGAACAACAACACTCCTCCGGATACATTGTTGGGTTTTGTGCCCTAAATAAAACCCATTTCGATATAATCAGATTTACTTATTAATAAAGATCAGAAATAA
+
FJJFJJAFJFJJ<JFFFJ<FJJJJJJJJJJJJJFJJJJJ--FJFJJAJAFFJF<-FAFJJJJ--7AJ-FFAJJJFJJJAFFFJ<FAJJJ7F-AJA<FFJJ-FFFFAF<FA-77FFA--AF--AFJJF

.... um ..... they're swapped! R/F ....?!
So if raw is R1F and R2F
phix contaminat producest R1F R2f
phix then super-deduper produces R1F R2F
then phix -> sd -> Adapter trim produces R1F R2RC
so reads end up ---> ---> instead of ---> <---
and the 
phix -> sD -> overlapper produces
R2F R1F

From Matt's chat earlier.

**Comment by msettles** [comment]
Thinking about it more, this has to be some weird edge case, otherwise nothing would overlap after adaper trimmer as R2 is RC?

 

Matt

**Comment by dstreett** [comment]
Definitely is an edge case.

In the algorithm, R1 always has to be larger than R2 (it allows us to have some assumptions). So, I do a swap when R1 is shorter than R2, do the algorithm and swap back. It is this swap that is messing everything up. I just need to add in an additional RC when swap is true.

**Comment by msettles** [comment]
So you think this only happened when I trimmed R1 and it wasn’t noticed before as that’s not ‘usual’ the R1/R2 swap I get, it’s the RC part that’s got me a little confused

 

Mat

**Comment by dstreett** [comment]
Long story short, I'm a dumbass.


`unsigned int check_read(PairedEndRead &pe , const double misDensity, const size_t &minOver, const size_t &checkLengths, const size_t kmer, const size_t kmerOffset, const size_t minLength, bool noFixBases = false ) {
    
    Read &r1 = pe.non_const_read_one();
    Read &r2 = pe.non_const_read_two();

    bool swapped = false;
    /*Read1 is always longer than Read 2)*/
    if (r1.getLength() < r2.getLength()) {
        std::swap(r1, r2);
        swapped = true;
    }
    ....
    if (swapped) {
        std::swap(r1, r2);
        r2.set_read_rc();
    }
    //we need to check if overlapper is greater than min length;

    return overlapped;
}
`

I just need to remove the set_read_rc() set in swap and we should be good to go. I can hit it here in a couple hours when I get off.

**Comment by msettles** [comment]
Ah, so at one you much have thought if it was swapped it also needed RC and ah no. Great so I see 2 fixes, 

 

in adapter trim need to remove r2.set_read_rc();

and

in overlapper need to have the check at end, if swapped need to swap back before output, should think more about the effect of this on strand. What is the effect of swapping R1 ß> R2 on overlapped reads that are stranded

 

Your working today????

 

Matt
