### ISSUE TITLE
Recent changes to how the stats file is handled seem to have broken creation of the stats file 

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#118]
Using:
commit 2f2a57b7401e1da65a722ba4479a71ee8f87df7a (HEAD -> master, origin/master, origin/HEAD)
Merge: 329f7d9 e8fd755
Author: Matt Settles <mattsettles@gmail.com>
Date:   Wed Jan 10 06:39:02 2018 -0800

If I try to run stats (also tested with super-deduper) I get the following:
$ /bio/HTStream/build/bin/stats -1 ../sample2_R1.fastq.gz -2 ../sample2_R2.fastq.gz -L stats.log

        Unhandled Exception: Error: Cannot write to stats.log: No such file or directory

If I create an empty file:
$ touch stats.log
$ stats -1 ../sample2_R1.fastq.gz -2 ../sample2_R2.fastq.gz -L stats.log

No problems.

**Comment by msettles** [comment]
addressed in #121
