### ISSUE TITLE
Bitwise and should be operator and

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#119]
https://github.com/ibest/HTStream/blob/872e9b90916c3959893adaff96758c77657d216c/Super-Deduper/src/super-deduper.h#L34

@msettles - Did you want this to be a bitwise or logical AND?

**Comment by msettles** [comment]
logical, just don't want to output  when 0, will fix in my next commit

**Comment by msettles** [comment]
addressed in #121
