### ISSUE TITLE
AT Repeat AT-Trim results

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#124]
Little issue @samhunter pointed out this morning.

This might be less than ideal behavior: If mismatches allowed is 3 and min trim is greater than 6. . . this is how the algorithm will behave.

<Read>TATAT<CUT>ATATAT

The ATATAT will be cut out of the read. Ways to get around this issue is to either set the mintrim greater than 7 OR allow fewer mismatches.

I don't think this is a critical issue, but it is a limitation of the algorithm.

**Comment by msettles** [comment]
OR maybe do something with polyA, stretches of As, as matching just length 1 should never be enough


Matt

**Comment by monicabritton** [comment]
Monica's 2cents:  I've never had a need to find/remove "ATATAT...", but it is very desirable to trim long polyA and polyT stretches from reads, particularly from RNA-Seq reads prior to transcriptome assembly.  Maybe an option to trim any read with a stretch of more than some number of the same base (any base), like say:
--polytrim 10
would trim any read that has at least 10 bases that are poly-anything (ACGT).

**Comment by msettles** [comment]
Monica, the algorithms point is to trim polyA/T, but because of the way the alg is written it will also trim something like ATATAT as its based on total mismatches not stretches, which isn’t the desired behavior.


Matt

**Comment by msettles** [comment]
This is addressed in the new algorithm for polyATTrim
