### ISSUE TITLE
Adapter-Trimmer may sometimes keep the lower quality base (not confirmed)?

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#126]
@dstreett is looking into this but doesn't think it should be possible.

@msettles please post the example reads you found where this appears to happen.

**Comment by dstreett** [comment]
Simplest case works it seems.

```
$ cat testing_R1

@Test_R1
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

$ cat testing_R2

@Test_R2
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC
+
#########################################

$ ./hts_Overlapper/hts_Overlapper -1 testing_R1 -2 testing_R2 -O

Test_R1 TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA?CCCCCCCC################################

```

**Comment by msettles** [comment]
Here was the read

 

# Read 1

@J00113:318:HKMFTBBXX:8:1101:1022:1226 1:N:0:NACGTGAT

NTTTGTAGGGCAGAAAAATTCTGCCTGACCTTTCCCATCTTCCTGATGATGTTAACAAACGACAGCCACTGAGGGCACAGGAGGGGGCTCTACACAGGCCAAGAGCTACAGGCTACAGTCTGAGCACAGAAAACCCTCCAGCTCCAGCAG

+

#AAAAJJJJJJJJJJJJJJJJJJJJFJFJJJJJJJJJJJFJJJFJAJFJJFFJFJJJJJJJJJJFJJ-FJJJJJFJJJJJ7JFJFJJAA<JJJFJFFJJJJJJJJJJJJJJJJJJJJJFAAF-F7FFAJJJJJFJJFFJJFJ7FJJFFJJ

# Read 2

@J00113:318:HKMFTBBXX:8:1101:1022:1226 2:N:0:NACGTGAT

NCTGGAGCTGGAGGGTTTTCTGTGCTCAGACTGTAGCCTGTAGCTCTTGGCCTGTGTAGAGCCCCCTCCTGTGCCCTCAGTGGCTGTCGTTTGTTAACATCATCAGGAAGATGGGAAAGGTCAGGCAGAATTTTTCTGCCCTCCAAAGCG

+

#AAFFJJFJJJFJJJAAJJJJJJJJFJFJJJJJJJJJJJJJJJJ7-FAJJJJJJJJFAFFFFJFJJJJJJJJ7FJJ7JFJFJJJFJFJAAAJFJJJJFFFJJ<J<FJ-JJ--7A7<JAFJJJ<FJJJJJ<AF<AAF<-<)<))77-<--7

 

 

# Read after overlapping

@J00113:318:HKMFTBBXX:8:1101:1022:1226 1:N:0:NACGTGAT

CTTTGGAGGGCAGAAAAATTCTGCCTGACCTTTCCCATCTTCCTGATGATGTTAACAAACGACAGCCACTGAGGGCACAGGAGGGGGCTCTACACAGGCCAAGAGCTACAGGCTACAGTCTGAGCACAGAAAACCCTCCAGCTCCAGC

+

IIII("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII&B

**Comment by msettles** [comment]
HMM, so I just ran exactly what you did with my read, and got the correct result, not what Jessie got

 

Will now run on our linux box (just ran on my computer) see if it changes, if its still correct, I’ll need to find out EXACTLY what she did.

 

Matt

**Comment by dstreett** [comment]
Yeah, dig into a bit. The overlapping code is solid and unit tested. Looking at the code, not sure how it would be possible.

If this behavior is reproducible, that could be an issue with the core code, which would be great to catch now rather than later. Let me know if you need any help.

**Comment by msettles** [comment]
OK found it, its in adapter trim (ish), overlapper alone correct result, adapter trim followed by overlap, wrong result, adatertrim trun off fixBases followed by overlapper correct result

 

msettles@ganesh: ~$hts_Overlapper -1 r1.fastq -2 r2.fastq -O

J00113:318:HKMFTBBXX:8:1101:1022:1226 1:N:0:NACGTGAT CTTTGTAGGGCAGAAAAATTCTGCCTGACCTTTCCCATCTTCCTGATGATGTTAACAAACGACAGCCACTGAGGGCACAGGAGGGGGCTCTACACAGGCCAAGAGCTACAGGCTACAGTCTGAGCACAGAAAACCCTCCAGCTCCAGC                "IIIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIID

msettles@ganesh: ~$hts_AdapterTrimmer -1 r1.fastq -2 r2.fastq -O | hts_Overlapper -S -O

J00113:318:HKMFTBBXX:8:1101:1022:1226 1:N:0:NACGTGAT CTTTGGAGGGCAGAAAAATTCTGCCTGACCTTTCCCATCTTCCTGATGATGTTAACAAACGACAGCCACTGAGGGCACAGGAGGGGGCTCTACACAGGCCAAGAGCTACAGGCTACAGTCTGAGCACAGAAAACCCTCCAGCTCCAGC                IIII("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII&B

msettles@ganesh: ~$hts_AdapterTrimmer -X -1 r1.fastq -2 r2.fastq -O | hts_Overlapper -S -O

J00113:318:HKMFTBBXX:8:1101:1022:1226 1:N:0:NACGTGAT CTTTGTAGGGCAGAAAAATTCTGCCTGACCTTTCCCATCTTCCTGATGATGTTAACAAACGACAGCCACTGAGGGCACAGGAGGGGGCTCTACACAGGCCAAGAGCTACAGGCTACAGTCTGAGCACAGAAAACCCTCCAGCTCCAGC                "IIIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIID
