### ISSUE TITLE
Unclear algorithm description for PolyATTrim

### ISSUE THREAD

**Issue by jfass** [ibest/HTStream#129]
The usage message for hts_PolyATTrim talks about moving from the 5'-ends of reads and expanding (?) towards the 3'-end. Is this accurate? It seems to work from the 3'-end towards the 5'-end ... or in any case that would seem to be preferable because it'll trim poly-As that are immediately *inwards* from adapter sequences trimmed by a previous step (in what would be a common pipeline).

There's an option to turn off 5' trimming, and to turn off 3' trimming. How does that affect the algorithm as described currently (above)? Clarifying this would be good.

Or I'm missing something!
Thanks.

**Comment by msettles** [comment]
I'm not actively working on this.

**Comment by msettles** [comment]
This is getting a new algorithm so closing
