### ISSUE TITLE
HTStream doesn't maintain read (R1, R2...) identifiers in header after cleaning

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#133]
In recent (CASAVA 1.8 format) Illumina data, read 1 has a name that looks like this:
@M01380:91:000000000-BM874:1:1101:16232:1728 **1**:Y:0:CCTTAACG+TCAAGTGG

While read 2 has a name that looks like this:
@M01380:91:000000000-BM874:1:1101:16232:1728 **2**:Y:0:CCTTAACG+TCAAGTGG

Where the value in bold indicates the read identity (read 1 or read 2)

After HTStream:
Read1:
@M01380:91:000000000-BM874:1:1101:23353:1988 **1**:Y:0:CCTTAACG+TCAAGTGG

Read2:
@M01380:91:000000000-BM874:1:1101:23353:1988 **1**:Y:0:CCTTAACG+TCAAGTGG

The designation for read1 and read2 is lost. The Illumina standard has changed a number of times, and there are many other standard formats for Fastq headers, so it probably doesn't make sense to try and support everything. Is this a bug in HTStream? If so, how should we fix it?

**Comment by samhunter** [comment]
My vote is that we change the reader/writer so that we store the first and second read ID (so we have 6 elements in the tab format instead of 5 for PE). This is the simplest solution. It does require a slight amount of additional memory, but the app is streaming so it shouldn't be much.
Additionally it turns out that bowtie2 now supports -tab5 and -tab6 format and streaming input, so using a 6-field format will not break compatibility with that.

**Comment by msettles** [comment]
Issue resolved in latest update, now uses tab6 format
