### ISSUE TITLE
hts_SeqScreener does not work with ambiguous bases in fasta file

### ISSUE THREAD

**Issue by najoshi** [ibest/HTStream#134]
hts_SeqScreener does not work with a fasta file that has ambiguous bases, and the error message is completely useless.

**Comment by msettles** [comment]
Hmm, how best to actually handle this??? Could recode each ambiguity code as one of the possibilities, or make kmers from all possibilities?

**Comment by msettles** [comment]
Fixed in pull request #138 updated version # to 0.3.2
