### ISSUE TITLE
Super-Deduper summary data

### ISSUE THREAD

**Issue by Tgrandis** [ibest/HTStream#143]
Hello:

Thanks for the new Super_Deduper. It runs at markedly less RAM.. only about 8% of older version. The installation was not exactly smoothless, but I got it to work. I have two little issues.

One is in the on-line usage information (https://ibest.github.io/HTStream/apps.html), the command to get to see the options for the programme is written as "super-deduper --help". It should of course be "hts_SuperDeduper --help".

The other issue is that in the old version, the programme displayed some summary statistics on the terminal when finished, which it does not do in the new version.

super_deduper -s 6 -l 55 -p ~/Xylia_2018/Xxyl01 -1 ~/Xylia_2018/Xxyl01_1.fq.gz -2 ~/Xylia_2018/Xxyl01_2.fq.gz
Final:| reads: 41354354 | duplicates: 6857380 | reads_written: 34496974 | percent: 16.58 | discarded: 40028 | total_seconds: 312.47 | reads/sec: 132344.65

Maybe there should be an option to display these statistics as I think they are very informative.

Cheers,
Hugo

**Comment by dstreett** [comment]
Hi @Tgrandis , thank for the note. As far as the stats go, check out `stats.log` _or_ supply the program with `-L [ --stats-file ] arg (=stats.log)  String for output stats file name`. It is a JSON file that stores the metrics.

Thanks for the heads up about SD's help text being wrong as well. I will put up a PR later today with the fix.

**Comment by Tgrandis** [comment]
Hi David: 

Thanks for directing me to the log file. Indeed, the
numbers are there, just missing the % duplicates... but that is easy
enough to calculate. 

Thanks for making all these niceties available
for people like me. 

Cheers, 

Hugo 

On Thu, 20 Sep 2018 13:02:36
+0000 (UTC), David Streett wrote: 

> Hi @Tgrandis [1] , thank for the
note. As far as the stats go, check out stats.log _or_ supply the
program with -L [ --stats-file ] arg (=stats.log) String for output
stats file name. It is a JSON file that stores the metrics. 
> 
> Thanks
for the heads up about SD's help text being wrong as well. I will put up
a PR later today with the fix. 
> 
> --
> You are receiving this because
you were mentioned.
> Reply to this email directly, view it on GitHub
[2], or mute the thread [3].

-- 
Hugo Volkaert
Plant Molecular Genetics
and Biotechnology Laboratory
Plant Biotechnology Research Unit
National
Center for Genetic Engineering and Biotechnology
A312 Center for
Agricultural Biotechnology
Kasetsart University - Kamphaengsaen
Campus
NakornPathom
73140
Thailand
phone +66 34353217 ext 305
fax +66
34353222
  

Links:
------
[1] https://github.com/Tgrandis
[2]
https://github.com/ibest/HTStream/issues/143#issuecomment-423174537
[3]

**Comment by dstreett** [comment]
@samhunter did an great job updating the `HTStream` page https://ibest.github.io/HTStream/#hts_SuperDeduper . It seems to be correct now, so I'm going to close this issue. Please let us know if you run into any more issues and thank you for using HTStream!
