### ISSUE TITLE
Interleaved output broken when one read is discarded by hts_QWindowTrim

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#149]
If hts_QWindowTrim is run with interleaved output on the records below (e.g. hts_QWindowTrim -I testI.fastq -i) it will discard read2 for both records. 

This results in an interleaved output file which contains only Read1 (breaking the interleaved format).

This can be resolved by either: 1) not using interleaved format (in which case, orphaned reads go to the "SE" output file), 2) adding the "-n" switch to discard orphaned reads. is 

This is a bug, but probably not high priority to fix since interleaved format is such a distasteful way to store sequencing data.

Example input:

@MISEQ03:189:000000000-A5290:1:2114:15705:28352 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAGACGGAGACAGCGCATTAATATTATCAAGCCACATCCGTGACCCAATCGATACGAAAGCACCACACATTTACACACTCCTCGCAACGACGCCAGACCCGACAAGCACAACTCTGAACACACCACACTGACAAACATCAC
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?1?//?DC###################################################################################################################################
@MISEQ03:189:000000000-A5290:1:2114:15705:28352 2:N:0:TGACC
GATGGGGAGAGCGGCGGGGTGGGGAAAAGCGGAGATCTCGGGGGGCGGCGGGAACTTAAAAAAAAAAAACAAAAGAAAGCAAACGCTCCGAACGAAAATGCCGCGCCATTTACACAAGACTTTCTTCAACGATAAACATAGCCAAAGGGAGCGATCGGCGACGAATCTCAAATAGCGTACCACAACCACACCCACACGCAACCACTAGCCAAAGCATGCCACGTCAGCCACCCAACTAGCGCTCAGCGACC
+
1111111111111A0AAE#########################################################################################################################################################################################################################################
@MISEQ03:189:000000000-A5290:1:2114:15705:28353 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAGACGGAGACAGCGCATTAATATTATCAAGCCACATCCGTGACCCAATCGATACGAAAGCACCACACATTTACACACTCCTCGCAACGACGCCAGACCCGACAAGCACAACTCTGAACACACCACACTGACAAACATCAC
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?1?//?DC###################################################################################################################################
@MISEQ03:189:000000000-A5290:1:2114:15705:28353 2:N:0:TGACC
GATGGGGAGAGCGGCGGGGTGGGGAAAAGCGGAGATCTCGGGGGGCGGCGGGAACTTAAAAAAAAAAAACAAAAGAAAGCAAACGCTCCGAACGAAAATGCCGCGCCATTTACACAAGACTTTCTTCAACGATAAACATAGCCAAAGGGAGCGATCGGCGACGAATCTCAAATAGCGTACCACAACCACACCCACACGCAACCACTAGCCAAAGCATGCCACGTCAGCCACCCAACTAGCGCTCAGCGACC
+
1111111111111A0AAE#########################################################################################################################################################################################################################################

Output
$ cat hts_QWindowTrimINTER.fastq 
@MISEQ03:189:000000000-A5290:1:2114:15705:28352 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAG
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?
@MISEQ03:189:000000000-A5290:1:2114:15705:28353 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAG
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?

**Comment by msettles** [comment]
So you get a SE file with reads?? I think maybe in iohandler.h lines 207-214 might be successfully type casting SE reads as PE
    void write(const ReadBase &read) {
        const PairedEndRead *per = dynamic_cast<const PairedEndRead*>(&read);
        if (per) {
            write(*per);
        } else {
            throw std::runtime_error("SingleEndRead called in PairedEndReadOutInter::write");
        }
    }
