### ISSUE TITLE
Improvement Suggestion 

### ISSUE THREAD

**Issue by efratushava** [ibest/HTStream#150]
Hi

I'm using super_deduper program in hts.
I have a suggestion for improvement:
In the program, all reads with "N" are ignored.
Threre are times, when pepole needs also these reads.
Maybe you can add a flag that lets the user to decide whether to keep these reads or not.

Thank you!

**Comment by msettles** [comment]
@efratushava thanks for the comment, sorry but I can't think of a case where, for the purpose of duplicate identification, you would want to consider the "N" character. Also the way bases are encoded in hts (2-bit format) its not really possible. Your specific issue of wanting to include reads that contain an "N" in the SD key sequence (I assume in the case of a sequencer hiccup and all bases at say base-12 are "N") you can get around this by moving the key start and length parameters to be outside of the problematic base. IN practice a good run should have VERY few "N" in the key sequence location.
