### ISSUE TITLE
Merging into master

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#16]
When should we be merging into master? In the past, it always lagged pretty far behind.

**Comment by joe-angell** [comment]
I think we should merge into master soon, because current master is busted.  Maybe after the single end read is fixed #15.

**Comment by joe-angell** [comment]
we could just get rid of develop branch too as another option, and just have pr's that are tested before merging to master, and do version tagging on master.

**Comment by dstreett** [comment]
Yeah, agreed. Looking in #15 now.

I think I am sort of digging feature branch directly to master. Seems that would save us a step and an extra pull request. @samhunter Thoughts?

**Comment by samhunter** [comment]
Sounds good to me :)
