### ISSUE TITLE
hts_PolyATTrim has three "-i" switches

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#166]
**-i [ --skip_polyA ]                   Skip check for polyA sequence**
  **-i [ --skip_polyT ]                   Skip check for polyT sequence**
  -w [ --window-size ] arg (=6)         Window size in which to trim (min 1, 
                                        max 10000)
  -e [ --max-mismatch-errorDensity ] arg (=0.29999999999999999)
                                        Max percent of mismatches allowed in 
                                        overlapped section (min 0.0, max 1.0)
  **-i [ --perfect-windows ] arg (=1)     Number perfect match windows needed 
                                        before a match is reported  (min 1, max
                                        10000)**

**Comment by dstreett** [comment]
Are you asking for more `-i` options?

Jk, I can look into it tonight - great catch, thank you @samhunter!

**Comment by samhunter** [comment]
Actually there are 4... -i is also for --interleaved-output. I'm working on fixing it now.

**Comment by msettles** [comment]
Fixed in #186
