### ISSUE TITLE
HTStream needs more informative logs

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#175]
To help with the reproducible research problem, bioinformatics apps should be logging version, parameters, and as much other pertinent information as possible (see https://twitter.com/mikelove/status/1206202957370417152). This should be easy to add in the HTS logs. 
Some things to log could include: version, and maybe full path to exe, command line parameters, working directory, date and time, full path to input files (or "stream"), and maybe more?

**Comment by msettles** [comment]
brach reproducability is meant to do a lot of this but I'm struggling to get the command line recorded into the json file, boost::any isn't easy to type cast our large argument set

**Comment by msettles** [comment]
Pretty much all handled in #189 at least keep all the command line options and version in order to recreate
