### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by pikabika** [ibest/HTStream#177]
Have a user reporting the error:

Unhandled Exception: regex_error

when attempting to run any of 
hts_SuperDeduper
hts_SeqScreener
hts_AdapterTrimmer
hts_Stats

HTStream compiled with stock GCC on CentOS 7 (4.8.5) 

Any Ideas?

**Comment by samhunter** [comment]
Hum, any chance that more details could be provided on how exactly this was run?

**Comment by samhunter** [comment]
Hey Benji, we recently removed regex requirements for htstream, in the very latest commit. I will be releasing a new version soon, but it might fix this issue.

**Comment by msettles** [comment]
@pikabika  Benji can you still reproduce?? This should be fixed and if so closed

**Comment by pikabika** [comment]
This can be closed.  End user reports it working now
