### ISSUE TITLE
Weird loading of the gitio pages

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#27]
Hey, @bioSandMan ,

There is something a bit odd when the gitio pages load. It first goes to an HTML like page (split second) then reformats to look correct. Could you look into why this is happening?

Thanks!

**Comment by bioSandMan** [comment]
@dstreett  It is due to my desire to have re-usable header and footer. Take a look at this template and let me know if this is better.

https://biosandman.github.io/HTStreamGHPage/pages/index.html

**Comment by dstreett** [comment]
Yep, the loading seems much better. Thanks!
