### ISSUE TITLE
Drop down change

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#28]
Hi, @bioSandMan

I am going to be a pain and change my mind about the drop down. Anyway you could just put the drop down options directly under the drop down button.

That way the user can immediately find all the Application of interest and it isn't hidden in the slightest.

Thanks!

**Comment by bioSandMan** [comment]
Hi @dstreett 

Please take a look at this template and let me know if this is what you were intending. 

https://biosandman.github.io/HTStreamGHPage/pages/index.html

**Comment by dstreett** [comment]
Closer - could you pre-expanded the drop downs, without the option to collapse?

The idea is the if someone needs help with an application, they can find it pretty much immediately.

**Comment by bioSandMan** [comment]
As discussed this has been changed in the current gh-pages branch.
