### ISSUE TITLE
Remove images

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#29]
Hey, @bioSandMan 
(sorry to spam you with these)

Let's remove the picture place holder stuff.

I'm not sure how many applications will have corresponding pictures but I image maybe only 1 or 2.  If they do need a picture, I can just put them inline.

Let me know if you have any questions, about this one or any of the issues I just submitted.

Thank you!

**Comment by bioSandMan** [comment]
@dstreett 
Ok. This is the same template I used in response to the other requests. There are several UI templates for you to copy and take advantage of. https://biosandman.github.io/HTStreamGHPage/pages/index.html
