### ISSUE TITLE
Overlapper SE file has no IDs and quality strings appear to be wrong and/or made up of sequences

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#39]
@ID
ATGCTCACTACCACTCTCTCCGTACTGGAATATTCATCTACTCCCATTTTGCTGACTCTTATACCTCTCAGCGACATTTCCGTGCTTGGGGTCATATCAGGCAATATTCCGATCATTCCCATTACACTGTCAATGGGTTCAATCCCCCAGTTCTGGAAAAGCACTTTTGCATCCTTTTGGAAATGCCTCAAGAGTTGGTG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ID
TTTCCCCAACGATTGCTCCCTCCTCAGTGAAAGCCCTTAGTAGTATCAAAGTTTCTAATCGATTAAAGATCACACTGAAGTTCGCTTTCAGTATAATGTTCTTTTCCATGATCGCCTGGTCCATTCGCACATAAAGAGGGCCTATTATCTTTTGCCTAGGCATGAGCATGAACCAGTCTCGTGACATTTCCTCGAGGGTCATGTCAGCTATGT
+
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ID
NCGCCAAATATGCCTCTAGTTTGTTTCTCTGGCACATTCCGCATTCCTGTTGCCAATTTCAGAGTGTTTTGCTTAACATATCTGGGACAGACCCCATATGTGATCCTGTTTACATTTTGAAAGGGTTTGTCATTGGGAATGCTTCCATTTGGAGTAATGCATTCAGATTTGCAATTGACAATGGGTGCATCTGATCTCATTATTGAGCTTTTCCCACTCTGTATTTTGAAGTAACCCCGAGGGGCAATTAGATTCCCTGTGCTGTTAATCAAAAGTATGTCTCCCGGTTTTACTATTGT
+
#<0<BHIHHHHEGHHEHHHI?GGHIIEEHIE1DHHIIFHHFCDHEHEH7III4IIIIIIIIIIIIIIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII=;GI<<IIGIIIIIIATTCCCTGTGCTGTTAATCAAAAGTATGTCTCCCGGTTTTACTATTGT
@ID
GGGCACCCCAGCTCAATCCTATTGATGGACCACTACCTGAAGATAATGAACCAAGTGGGTATGCACAAACAGACTGTGTCCTGGAGGCCATGGCTTTCCTTGAAGAATCCCACCCAGGGATATTTGAGAATTCATGCCTTGAAACAATGGAAATTGTCCAACAAGCAAGGGTGGATAAACTAACTCAGGGTCGCCAGACTTATGATTGGACATTAAATAGAAATCAACCGGCAGCAACTGCATTGGCCAACACCATAGAAGTTTTTAGATCAAATGGTCTCACAGCTAATGAGTCAGGAAGGCTAATAGATTTCTTAAAAGATGTAATGGAATCAATGGATAAAGAGGAAATAGAGATAACAACACACTTTCAAAGAAAAAGGAGAGTAAGGGATAACATGACCAAGAAGATGGTCACACAA
+
DCDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIHHHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIHIIIIIIIIIIIIIHIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIACCATAGAAGTTTTTAGATCAAATGGTCTCACAGCTAATGAGTCAGGAAGGCTAATAGATTTCTTAAAAGATGTAATGGAATCAATGGATAAAGAGGAAATAGAGATAACAACACACTTTCAAAGAAAAAGGAGAGTAAGGGATAACATGACCAAGAAGATGGTCACACAA
@ID
AATGTACTCAAATGCAAATGTTGCACCTAATGTTGCCTTTTTGGCAGGCCCACATAATGAACCCCAGCAGAACAACACAAAGCAAAAAGCATGACATGGCAAAGGAAATCCATAGGATCCAATCTTTGTATCCTGACTTCAGCTGAACACCTTTGATCTGGAACCGATTGCTTAATGCCTCGTCTCTGTATAC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ID
CCTCTGCTGCTTGTTCACTTGACCCAGCCATTTGTTCCATGGCCTTAGCTGTTGTGCTGGCTATTACCATTCTGTTCTCGTGCCTGATTAGTGGATTGGTTGTTGTCACCATTTGTCTATGAGATCGATGCTGGGAATCAGCAATCTGTTCACAGGTTGCGCATACCAGACCAAATGCCACCTCAGTGGCGACAGTCCCCATTCTGTTGTATAT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ID
NCAGAATGCCCTCAATGGGAATGGTGACCCAAACAACATGGACAAGGCAGTCAAACTGTATAGGAAACTAAAACGAGAAATAACATTCCATGGGGCCAAAGAAGTAGCACTCAGTTATTCTGCCGGTGCACTTGCCAGTTGCATGGGCCTCATATACAACAGAATGGGGACTGTCGCCACTGAGGTGGCATTTGGTCTGGTATGCGCAACCTGTGAACAGATTGCTGATTCCCAGCATCGATCTCATAGACAAATGGTGACAACAACCAATCCACTAATCAGGCACGAGAACAGAATGGTAATAGCCAGCACAACAG
+
#<DDDIGHHHHIIIIIHHIIHIHHIEHIHIHHIIIIHHHIHIIIIHIIIHCEHIHHHIHHIHIIHHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"AAATGGTGACAACAACCAATCCACTAATCAGGCACGAGAACAGAATGGTAATAGCCAGCACAACAG
@ID

**Comment by samhunter** [comment]
It is difficult to see in the text I pasted above, but view it fixed-width in a txt editor. It seems like the last piece of the quality string is the read!

**Comment by dstreett** [comment]
Copy paste error
```
finalQual += seq2.substr(maxLoop, r2.getLength() - maxLoop);
```
Should have been . . .
```
finalQual += qual2.substr(maxLoop, r2.getLength() - maxLoop);
```

**Comment by samhunter** [comment]
ID text still blank:

@ID
ATGCTCACTACCACTCTCTCCGTACTGGAATATTCATCTACTCCCATTTTGCTGACTCTTATACCTCTCAGCGACATTTCCGTGCTTGGGGTCATATCAGGCAATATTCCGATCATTCCCATTACACTGTCAATGGGTTCAATCCCCCAGTTCTGGAAAAGCACTTTTGCATCCTTTTGGAAATGCCTCAAGAGTTGGTG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ID
TTTCCCCAACGATTGCTCCCTCCTCAGTGAAAGCCCTTAGTAGTATCAAAGTTTCTAATCGATTAAAGATCACACTGAAGTTCGCTTTCAGTATAATGTTCTTTTCCATGATCGCCTGGTCCATTCGCACATAAAGAGGGCCTATTATCTTTTGCCTAGGCATGAGCATGAACCAGTCTCGTGACATTTCCTCGAGGGTCATGTCAGCTATGT
+
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

**Comment by dstreett** [comment]
It is a feature to reduce memory. ;) Just kidding, Fixed in N-Remover, will close once merged into master.
