### ISSUE TITLE
Q-window-trim generates PE files, but crashes on SE write (maybe?)

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#41]
$ ~/HTStream/build/Q-Window-Trim/q-window-trim -1 202_S14_R1_001.fastq.gz -2 202_S14_R2_001.fastq.gz -f -p htq -m 200

        Unhandled Exception: No write_read class, only accessable with SE

$ ll
total 416
drwxrwxr-x 2 shunter grc   4096 Dec 30 01:27 ./
drwxr-xr-x 8 shunter grc   4096 Dec 30 01:23 ../
lrwxrwxrwx 1 shunter grc  341682103 Dec 30 01:26 202_S14_R1_001.fastq.gz
lrwxrwxrwx 1 shunter grc  366655813 Dec 30 01:26 202_S14_R2_001.fastq.gz 
-rw-rw-r-- 1 shunter grc 204735 Dec 30 01:27 htqPE1.fastq
-rw-rw-r-- 1 shunter grc 204243 Dec 30 01:27 htqPE2.fastq

**Comment by dstreett** [comment]
Nope, just me being a noob. Fixed in N-Remover, I will close once merged into master.

It was a virtualized function that I forgot to make within SE reads, causing it to use default behavior.

**Comment by samhunter** [comment]
Great, thanks!
