### ISSUE TITLE
gh-pages Update

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#46]
@msettles @samhunter (Someone tag Alida as well). Hi, all. :) 

I'm starting to update the website. It is located here   https://ibest.github.io/HTStream/ . Please, feel free to update gh-pages (_layout/*.html) directly or submit issues/enhancements.

It is looking real rough right now, but it is a start. I will continue to add to it and edit it the next couple of weeks. There is already some formatting / CSS stuff I need to iron out - however, don't hesitate to open an issue about anything.

**Comment by samhunter** [comment]
The web page has been rebuilt using a single index.html which isn't fancy but will hopefully be simple to maintain.
