### ISSUE TITLE
Add an option to discard orphans to all trimming tools

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#51]
If any trimming tool removes enough bases that a read would be discarded, have the option of discarding the other read in the pair as well. This will allow the user to know that all reads are paired if needed.

**Comment by dstreett** [comment]
Hey, @samhunter, here is a temporary fix for this issue.

` q-window-trim  . . . |  awk '{ if (NF==5) print $0; }' | overlapper . . . `

**Comment by dstreett** [comment]
This feature is to be added to - Cut-Trim, PolyAT-Trim, Q-Window-Trim.

**Comment by samhunter** [comment]
Does the OrphanDiscard branch install executables? It doesn't appear to on my end, but maybe I am doing something silly?

**Comment by msettles** [comment]
Think this is working, closing for now, reopen if not after further testing
