### ISSUE TITLE
Help text, Version information and description

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#53]
For all programs, the help-text output should note that the program is part of the HTStream package, probably with a link to the GitHub repo and a short description of what it does, and preferably version information (I also think it would be amazing if the git commit hash was displayed but that might be too much of a PITA).

Currently the "-v" switch reports nothing.

**Comment by msettles** [comment]
I think we should also have sub application versions as well, so a HTStream version that represents changes to src/common and app changes that represent changes to the Add. thoughts?

**Comment by msettles** [comment]
Done
