### ISSUE TITLE
It appears that -A still prints "Program" in the stats log file

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#54]
EG:
`Program TotalRecords    R2_Discarded    R1_Discarded    R2_Length       SE_Out  SE_Length       Ignored TotalReadsInput PE_In   PE_Out  SE_In   SE_Left_Trim    Sins    Replaced        SE_Discarded    R2_Right_Trim   R1_Left_Trim    SE_Right_Trim   R1_Right_Trim   R1_Length       R2_Left_Trim    Overlap_BPs     Lins                                                                                                                                                        
Super-Deduper   267139  0       0       66367161        0       0       0       0       0       264411  0       0       0       2728    0       0       0       0       0       66367161        0       0       0
Program Q-Trim  264411  14      0       65862254        14      0       0       0       0       264397  0       0       0       0       0       496200  231     0       440264  65926666        5193    0       0
Program Overlapper      264411  0       0       24600101        163746  41630620        0       0       0       98694   0       0       0       0       1971    0       0       0       0       24669593        0       0       0
`

**Comment by samhunter** [comment]
Okay, that totally didn't work:

Program TotalRecords    R2_Discarded    R1_Discarded    R2_Length       SE_Out  SE_Length       Ignored TotalReadsInput PE_In   PE_Out  SE_In   SE_Left_Trim    Sins    Replaced        SE_Discarded    R2_Right_Trim   R1_Left_Trim    SE_Right_Trim   R1_Right_Trim   R1_Length       R2_Left_Trim    Overlap_BPs     Lins

Super-Deduper   267139  0       0       66367161        0       0       0       0       0       264411  0       0       0       2728    0       0       0       0       0       66367161        0       0       0

Program Q-Trim  264411  14      0       65862254        14      0       0       0       0       264397  0       0       0       0       0       496200  231     0       440264  65926666        5193    0       0

Program Overlapper      264411  0       0       24600101        163746  41630620        0       0       0       98694   0       0       0       0       1971    0       0       0       0       24669593        0       0       0

**Comment by msettles** [comment]
I'm not sure I like this stats output format, for one I can't tell what some of these actually mean, I get that you need something that will append as you go, but seems to leave out a lot of stats that are sub-app specific, and doesn't really allow for the flexibility of new apps (new stats) etc. Nor does it offer an easy way to summarize and then compare across samples. SO might I suggest a json formatted output, that can then be read into a post processing app (in R maybe) and certain keys can be picked up and summarized. One of the huge advantages in HTStream is that others can create apps that can also go into the stream, but abiding by a stats table may limit their usefulness, a json formatted file will then offer that flexibility.

**Comment by msettles** [comment]
no longer relevant
