### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by msettles** [ibest/HTStream#66]
Wondering what the verdict/timeline is for the possible conversion of application output stats to JSON. For me at least preprocessing stats are as important as the actual processed reads as they give SO much information on whether I can even use the data. So I can't really see moving over to HTStream to even test vigorously until there are good stats to review afterwards

**Comment by samhunter** [comment]
After discussion, we like the idea of JSON. David also needs to graduate however, and a ton of validation work and writing needs to be done to make that happen. So currently the plan is to tentatively try and get JSON support working as a ~2-3 day investment, then to make a decision based on the outcome of that testing.

**Comment by msettles** [comment]
To help ensure that investment time is productive, a conference call to talk about what is important and what isn’t to go into the output?


Matt

**Comment by msettles** [comment]
JSON stats are looking GOOD! Can't wait to make a nice R visual from it, we all need to finalize however the terminology. Closing for now however
