### ISSUE TITLE
Issues with install

### ISSUE THREAD

**Issue by msettles** [ibest/HTStream#68]
Now getting 

-- Install configuration: ""
-- Up-to-date: /share/biocore/software/lib/libhts_common.so
-- Up-to-date: /share/biocore/software/bin/super-deduper
-- Up-to-date: /share/biocore/software/bin/tab-converter
-- Up-to-date: /share/biocore/software/bin/polyATtrim
-- Up-to-date: /share/biocore/software/bin/q-window-trim
-- Up-to-date: /share/biocore/software/bin/cut-trim
-- Up-to-date: /share/biocore/software/bin/phix-remover
-- Up-to-date: /share/biocore/software/bin/overlapper
-- Up-to-date: /share/biocore/software/bin/n-remover
msettles@ganesh: build$phix-remover 0h
phix-remover: error while loading shared libraries: libhts_common.so: cannot open shared object file: No such file or directory
msettles@ganesh: build$phix-remover -h
phix-remover: error while loading shared libraries: libhts_common.so: cannot open shared object file: No such file or directory

**Comment by joe-angell** [comment]
You'll need to `export LD_LIBRARY_PATH=/share/biocore/software/lib`  or add that dir to your ld.so.conf.  I guess we should do a static link build just to avoid these issues and make it easier for people.

**Comment by msettles** [comment]
then that killed my LD reference to boost (has to be loaded by module first), so then 
export LD_LIBRARY_PATH=/share/biocore/software/lib:$LD_LIBRARY_PATH
work, a bit cumbersome

Matt

**Comment by msettles** [comment]
and thanks for the quick response

**Comment by joe-angell** [comment]
fixed in #69
