### ISSUE TITLE
phix-remover has two -s switches 

### ISSUE THREAD

**Issue by samhunter** [ibest/HTStream#92]
commit 91406338ba10c5f1e1b3cf57b1ca9ca720fd8822

  -s [ --stranded ]                    If R1 is orphaned, R2 is RC (for  
                                      stranded RNA) 
 -m [ --min-length ] arg (=50)        Min length for acceptable outputted read 
 -l [ --no-left ]                     Turns of trimming of the left side of  
                                      the read 
 -r [ --no-right ]                    Turns of trimming of the right side of  
                                      the read 
 -s [ --seq ] arg                     Please supply a fasta file - default -  
                                      Phix Sequence - default  
                                      https://www.ncbi.nlm.nih.gov/nuccore/962 
                                      6372

**Comment by msettles** [comment]
I removed 
        setDefaultParamsCutting(desc);
        setDefaultParamsTrim(desc);

As those options weren't even being used, freeing up the --seq, s to be used by phix-remover
