### ISSUE TITLE
Overlapping

### ISSUE THREAD

**Issue by msettles** [ibest/HTStream#98]
Plot of the histogram (which BTW should be nested better in the stats), see the big 2x spike right at 100bp, this has to be a false peak. Not sure what from?

![rplot](https://user-images.githubusercontent.com/649446/31101023-c2b9d0e2-a780-11e7-97af-14daec65836d.png)

**Comment by dstreett** [comment]
I'm assuming you are doing hiseq 2x100? I bet, I just was dumb and counted non-overlapped reads. I'll dive into right now.

**Comment by msettles** [comment]
Yes, 2x100, don’t think the count is high enough to be non-overlapping reads, but not sure. 

 

Also in the stats for overlapper, if we can nest the counts (exactly as you have them), but under key “histogram”

 

So 

 

Overlapper

                PE_IN

                PE_OUT

                ETC.

                HISTOGRAM

                                1

                                2

etc

 

will make it so much easier!


Matt

**Comment by msettles** [comment]
Maybe single end reads that go through overlapper (nothing to overlap)??

**Comment by dstreett** [comment]
Totally agreed with the sub histogram.

Seems it is something goofy I'm doing when calculating the overlap. 2x300 has a peak at 300. Ruled out single end adding to the count.

**Comment by samhunter** [comment]
Also seeing spike in PE300:

"295" : 1972,
"296" : 1939,
"297" : 1901,
"298" : 1917,
"299" : 1803,
"300" : 3627,
"301" : 1832,
"302" : 1879,
"303" : 1758,
"304" : 1864,

**Comment by msettles** [comment]
Ok, I fixed a bunch of the stats. Added some additional stats to phix-remover (just the number removed), modified the stats in 'stats' more relevant (also stats look to be correct now), and fixed all the stats in adapter-trimmer including nesting the histogram into a json array, I DID NOT change the algorithm at all, just output stats properly [I think, pretty sure]. NOW after running adapter-trimmer followed by overlapper, you get two different results, implying different algorithms, of differing algorithms. See below

{ "Phix-Remover_33082": {
    "Notes": "",
    "Inverse": 0,
    "SE_hits": 0,
    "PE_hits": 259756,
    "SE_Out": 0,
    "PE_Out": 4740244,
    "TotalFragmentsOutput": 4740244,
    "SE_In": 0,
    "PE_In": 5000000,
    "TotalFragmentsInput": 5000000
  }, "adapter_trimmer_33083": {
    "Notes": "",
    "R2_Adapter_BpTrim": 12921469,
    "R2_Discard": 0,
    "R1_Discard": 0,
    "PE_Discard": 37311,
    "SE_Discard": 0,
    "nins": 1420626,
    "sins": 718361,
    "R1_Adapter_BpTrim": 12921469,
    "lins": 2563946,
    "SE_Out": 0,
    "PE_Out": 4702933,
    "TotalFragmentsOutput": 4702933,
    "SE_In": 0,
    "PE_In": 4740244,
    "TotalFragmentsInput": 4740244,
    "histogram": [[1,0], [2,0], [3,0], [4,0], [5,0], [6,0], [7,0], [8,0], [9,0], [10,0], [11,0], [12,0], [13,0], [14,0], [15,0], [16,0], [17,0], [18,0], [19,0], [20,0], [21,0], [22,0], [23,0], [24,0], [25,0], [26,0], [27,0], [28,0], [29,0], [30,0], [31,0], [32,0], [33,0], [34,0], [35,0], [36,0], [37,0], [38,0], [39,0], [40,0], [41,0], [42,0], [43,0], [44,0], [45,0], [46,0], [47,0], [48,0], [49,0], [50,3356], [51,3632], [52,4096], [53,4322], [54,4651], [55,4877], [56,5088], [57,5193], [58,5203], [59,5534], [60,6016], [61,6573], [62,7260], [63,8104], [64,9040], [65,9450], [66,9876], [67,10778], [68,10836], [69,11537], [70,11782], [71,11788], [72,12136], [73,12855], [74,13292], [75,13490], [76,14365], [77,15038], [78,15554], [79,16227], [80,17133], [81,17213], [82,17387], [83,18478], [84,19642], [85,21355], [86,20625], [87,20290], [88,20736], [89,21038], [90,20722], [91,22135], [92,23408], [93,23926], [94,25659], [95,26574], [96,26671], [97,28480], [98,27324], [99,27616], [100,28420], [101,28473], [102,29050], [103,30332], [104,30043], [105,29198], [106,30895], [107,31231], [108,31504], [109,31978], [110,32152], [111,32570], [112,32837], [113,33077], [114,32016], [115,31118], [116,33522], [117,32787], [118,34167], [119,34106], [120,33150], [121,32595], [122,33285], [123,32754], [124,32774], [125,31795], [126,31734], [127,31696], [128,30931], [129,31968], [130,32107], [131,30839], [132,31121], [133,31794], [134,31023], [135,30495], [136,30979], [137,32367], [138,29731], [139,30911], [140,30918], [141,29864], [142,29713], [143,29706], [144,29551], [145,29144], [146,28722], [147,27611], [148,27744], [149,28570], [150,28057], [151,27922], [152,27012], [153,28291], [154,27694], [155,27578], [156,27842], [157,28210], [158,29112], [159,26965], [160,27258], [161,26935], [162,25717], [163,25715], [164,25668], [165,24839], [166,26175], [167,26804], [168,26173], [169,24978], [170,24739], [171,24595], [172,24657], [173,24257], [174,22682], [175,21880], [176,21418], [177,21262], [178,21373], [179,20663], [180,21061], [181,20764], [182,21635], [183,20713], [184,20856], [185,20738], [186,19885], [187,19887], [188,19468], [189,19548], [190,19200], [191,18652]]
  }, "Overlapper_33084": {
    "Notes": "",
    "R2_Adapter_BpTrim": 0,
    "R2_Discard": 0,
    "R1_Discard": 0,
    "PE_Discard": 0,
    "SE_Discard": 0,
    "nins": 1430684,
    "sins": 741843,
    "R1_Adapter_BpTrim": 0,
    "lins": 2530406,
    "SE_Length": 418248147,
    "SE_Out": 3272249,
    "PE_Out": 1430684,
    "TotalFragmentsOutput": 0,
    "SE_In": 0,
    "PE_In": 4702933,
    "TotalFragmentsInput": 4702933,
    "histogram": [[1,17293822569102704640]]
  }, "Stats_33085": {
    "Notes": "adapter-trimmer",
    "SE_BpLen": 418248147,
    "R1_BpLen": 142869521,
    "N": 109593,
    "G": 182698465,
    "SE_Out": 3272249,
    "T": 167000124,
    "PE_Out": 1430684,
    "R2_bQ30": 125523900,
    "R1_bQ30": 136544690,
    "C": 187148452,
    "A": 167030555,
    "TotalFragmentsOutput": 4702933,
    "SE_In": 3272249,
    "PE_In": 1430684,
    "SE_bQ30": 409969622,
    "R2_BpLen": 142869521,
    "TotalFragmentsInput": 4702933
  }
}

**Comment by dstreett** [comment]
@msettles You broke the test. :(

**Comment by dstreett** [comment]
All test in Adapter-trimmer now failing an off by one error with addition of the -1 to the getLength in the code. . . 

In this test for example - here is R1 and R2 (RCed). R1 is on top, R2 (RC) is on the bottom. The test expects to return the new R1 to be `ACCATAACATAAACC`, it is now returning `ACCATAACATAAACCA`. I think the test is preforming the correct action.

```
                               ACCATAACATAAACCATTAACCAAATTGGACATATCTCATCTATCCTTATACTTA
     GACGCAACTATACTCTATACTATATTACCATAACATAAACC
```

**Comment by dstreett** [comment]
Also, would you mind pushing to your own branch instead of master so someone could look over changes before they go into master?

**Comment by msettles** [comment]
Hmmm, interesting, so I think I know exactly where that is, and that
corrected an off by one in the histogram, so a 95bp read was reported as 94
on the histogram causing the pileup we saw on the read length. So to me
thay says thre was an off by one error in sins, but not in lins, fixing the
error I saw but now causing the new error?

Ya on the branch, sorry

**Comment by msettles** [comment]
Ok, I've found the relevant changes and reverted back. So now adapter_trimmer_test passes again (also editted stats test for the relevant changes.

So here are the 3 lines in question
54:    int r1_len = r1.getLength() -1;
55:    int r2_len = r2.getLength() -1;
and 
85:    unsigned int insert_length = maxLoop;

As is, adapter_trimmer_test passes all tests, BUT the histogram does not represent the read lengths correctly and has that bump at the read length, which is not real, there are not that many sequences of that size

if I change those lines to 
54:    int r1_len = r1.getLength();
55:    int r2_len = r2.getLength();
and 
85:    unsigned int insert_length = maxLoop + 1;

Now the histogram perfectly matches the actual read lengths in the resulting file, BUT the apps tests no longer pass. 

SO I'll let you figure that out now. All of my changes to stat output are still there.

There is also the pretty severe issue that it doesn't appear adapter_removal and overlapper produce the same overlaps?? I think they should?

**Comment by msettles** [comment]
This appear to be all fixed now, can revisit if shows up again
